package chaynik.mizu.domain.models.settings

import mizu.composeapp.generated.resources.Res
import mizu.composeapp.generated.resources.option_navigation_bar_label_visibility_always
import mizu.composeapp.generated.resources.option_navigation_bar_label_visibility_never
import mizu.composeapp.generated.resources.option_navigation_bar_label_visibility_only_selected
import org.jetbrains.compose.resources.StringResource

enum class NavigationBarLabelVisibility(val displayName: StringResource) {
	Always(Res.string.option_navigation_bar_label_visibility_always),
	OnlySelected(Res.string.option_navigation_bar_label_visibility_only_selected),
	Never(Res.string.option_navigation_bar_label_visibility_never)
}
